name: Testing the e2e test suites

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: bootstrap
        run: npm run bootstrap
      - name: build
        run: npm run build
      - name: e2e tests (cypress)
        run: npm run test:e2e
      - name: e2e tests (jest+playwright)
        run: npm run test:jest-e2e -- -ci
